### ISSUE TITLE
reST filter doesn't render header levels 1 & 2

### ISSUE THREAD

**Issue by benoistlaurent** [bartTC/django-markup#14]
# Problem

This classical restructured text formatting for section headers is not rendered as expected by django_markup.

```restructuredtext
********
Header 1
********

Header 2
========

Header 3
--------
```
Header 1 & 2 are pure and simply forgotten.

# Diagnotic

After some investigations, `django_markup` uses `docutils.core.publish_parts` to render rst. `django_markup` uses this code to render rst:

```python
def render(self, text, **kwargs):
    from docutils import core
    publish_args = {'source': text, 'writer_name': 'html4css1'}
    publish_args.update(**kwargs)
    parts = core.publish_parts(**publish_args)
    return parts['fragment']
```

`parts['fragment']` returns body content only from header 3, which is in agreement with the [docutils documentation](http://docutils.sourceforge.net/docs/api/publisher.html): 

> parts['fragment'] contains the document body (not the HTML <body>). In other words, it contains the entire document, less the document title, subtitle, docinfo, header, and footer.

# Proposed solution.

Use `parts['html_body']` instead of `parts['fragment']`:

```python
def render(self, text, **kwargs):
    from docutils import core
    publish_args = {'source': text, 'writer_name': 'html4css1'}
    publish_args.update(**kwargs)
    parts = core.publish_parts(**publish_args)
    return parts['html_body']
```

**Comment by bartTC** [comment]
Thanks for pointing this out, I wasn't aware! I'm going to setup some tests before merging it.

**Comment by bartTC** [comment]
This introduced backwards incompatible behavior. See the related commit https://github.com/bartTC/django-markup/commit/69b3e7c4b949cabe5a4a48832548d00deec0343c for more info.
