### ISSUE TITLE
vulnerable XSS django-markup

### ISSUE THREAD

**Issue by RaminFP** [bartTC/django-markup#18]
Hi,

XSS = ``` [XXX](                                      javascript:alert('123');) ```
{{ XSS|apply_markup:"markdown" }}

result : 
alert(123)

**Comment by bartTC** [comment]
Thank you, will look into this. I added a `safe_mode` default setting a while ago but I think this wouldn't cover it. Frankly, I'm not even sure if its a Markdown conversion issue. Refs #5.

**Comment by RaminFP** [comment]
Thanks , i use this 
```python
MARKUP_SETTINGS = {
    'markdown': {
        'safe_mode': True
    }
}
```
problem is resolved,
Thanks Again,
