### ISSUE TITLE
All filter dependencies not available in 1.4

### ISSUE THREAD

**Issue by michelts** [bartTC/django-markup#27]
Hi @bartTC 

If I install django-markup with all filter dependencies, in the 1.3 version it is ok, but the 1.4 version is buggy:

```
$ pip install django-markup[all-filter-dependencies]==1.4
    ...
    django-markup 1.4 does not provide the extra 'all-filter-dependencies'
```

I'm not sure if it is a bug in the requirements or a mistake from the docs, that still talk about this flag.

**Comment by bartTC** [comment]
Please use underscores, I changed this in 1.4 and forgot to update the docs.

**Comment by bartTC** [comment]
Docs are now updated and I made a 1.4.1 releaes with that.

**Comment by michelts** [comment]
Thank you @bartTC
