### ISSUE TITLE
Code blocks is not rendered correctly

### ISSUE THREAD

**Issue by lobothijau** [bartTC/django-markup#36]
How do I make the code block to rendered correctly. For example, if I write:

```
```python
from django.db import models</p>
class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
\```
```
then I expect the html to be:

```
<pre>
<code>
from django.db import models
class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
</code>
</pre>
```
How do I achieve that? I couldn't find the settings on the documentation. Thank you in advanced.

![Screenshot from 2020-08-17 21-19-34](https://user-images.githubusercontent.com/34962330/90406463-68d71680-e0cf-11ea-9b61-572600e98f85.png)

**Comment by bartTC** [comment]
Which markdown filter do you use? The builtin one?

**Comment by lobothijau** [comment]
Yes, I use the builtin one. 

```
{{object.content | apply_markup:"markdown" }}
```

**Comment by lobothijau** [comment]
I found the settings. I should config the extension list for fenced_code on settings.py. 

https://django-markup.readthedocs.io/en/latest/filter_settings.html?highlight=extensions#arguments-to-the-markup-filter

**Comment by lobothijau** [comment]
@bartTC other question. To enable ```python to be rendered as <code class="python">, what other settings should I use? I try the syntax on this page https://python-markdown.github.io/extensions/fenced_code_blocks/ but it's not working.
