### ISSUE TITLE
Cannot Use Django 3.2 With django-markup 1.7.1 

### ISSUE THREAD

**Issue by felix-gohla** [bartTC/django-markup#42]
Hi and thanks for your work on this library.

## Problem description

While installing the current version of `django-markup==1.7.1`, I noticed getting an error during installation:

```text
error: Django 3.2.18 is installed but django>=3.7 is required by {'django-markup'}
```

## Possible cause

I am using Django *3.2* in a project which seems to be incompatible due to the following constraint introduced in 16ab1bf:

https://github.com/bartTC/django-markup/blob/28a321873634138e1a99bbe1a124ea15b98cbc4b/setup.cfg#L30-L31

Is it intended to require that non-existing Django version? I also didn't find any hint in the README that the newest version shouldn't be compatible.

Thank you very much for your time.

**Comment by bartTC** [comment]
oh weird, why wasn't that caught by tox?

**Comment by bartTC** [comment]
https://pypi.org/project/django-markup/1.7.2/ should have fixed this. Thanks for the feedback!

**Comment by felix-gohla** [comment]
Nice. Thank you very much! 😊
