### ISSUE TITLE
ReST filter is vulnerable to XSS and file inclusion by default

### ISSUE THREAD

**Issue by spookylukey** [bartTC/django-markup#5]
The ReST 'raw' directive opens up a web site to XSS, and the 'include' directives opens you up to file inclusion by default:

http://docutils.sourceforge.net/docs/howto/security.html

It looks like MARKUP_SETTINGS allows you to specify the configuration you need to be secure. However, it isn't the default. Even if you had a default MARKUP_SETTINGS that was secure, if someone wanted to specify their own 'settings_overrides', it would be all to easy to forget to include the secure defaults.

It would be great if some secure defaults were hard coded, and they could only be overridden by explicitly reversing them:

    MARKUP_SETTINGS = {
        'restructuredtext': {
            'settings_overrides': {
                'raw_enabled': True,
                'file_insertion_enabled': True,
            }
        }

You might decide that the ReST filter should only be used on trusted inputs, or that implementing this would be a bit hacky. However, for something aimed at use on the web, I think that defaulting to secure would be so much better, and worth a bit of hackiness.

I can implement this if it would be accepted. However, I can't see any existing tests - do you have a test suite?

**Comment by bartTC** [comment]
Thank you for pointing this out and the deatils. I agree, this should be setup as default. That also applies to the `safe` argument of the Markdown filter. I'm going to cleanup all the filters and then come back.

> I can implement this if it would be accepted. However, I can't see any existing tests - do you have a test suite?

Now there is and it only took 3 years! 😳

**Comment by bartTC** [comment]
This is in and comes with the next release. I also added a default `safe_mode` for Markdown. Thanks again!

**Comment by spookylukey** [comment]
The defaults are the wrong way round - see pull request #15
