### ISSUE TITLE
Any chance of a new release?

### ISSUE THREAD

**Issue by richardbarran** [bartTC/django-markup#8]
As per subject line - I've found this a useful little package, simple and to the point. I'm using it on a site that runs Python 3.3/Django 1.7, and the latest release (0.4) does not work - but the Github HEAD works fine.

**Comment by Acanthostega** [comment]
Hi everybody,

@bartTC do you have any news on creating a new release of your package? It is really helpful for quick development. 

I can install it from github through pip but pip freeze doesn't generate correctly requirements when doing it from github, so an installation from pip is easier for lazy people like me to create requirements with single button press! Thank you!

**Comment by bartTC** [comment]
As I promised (\*cough* two years ago) it's high on my list.

The latest version is in pypi, it covers Django 1.8, 1.9, Python 2.7 and 3.5 in it's test suite. Right now its an alpha release but I only want to extend the tests to make it final. You can install it like a pre-release:

```
pip install -U django-markup --pre
```

Or more specifically:

```
pip install django-markup==1.0a1
```

I'll keep this issue open until the very final release. Which is very high on my list...

**Comment by richardbarran** [comment]
The alpha release works fine for me.

**Comment by bartTC** [comment]
v1.0 is released. Note that it dropps Pygments support and has other backwards incompatible changes.

https://pypi.python.org/pypi/django-markup/1.0

**Comment by richardbarran** [comment]
Many thanks!
