### ISSUE TITLE
url qoute needed

### ISSUE THREAD

**Issue by LennyLip** [bartTC/django-markup#9]
https://github.com/bartTC/django-markup/blob/master/src/django_markup/bundles/WikiCreole/creole2html.py

```python
>>> parse(u'[[test]] [[tset|test]]')
<p><a href="test">test</a> <a href="tset">test</a></p>

return u'<a href="%s">%s</a>' % (
            self.attr_escape(target), inside)
```

with "test", containing special characters, i think, need no escape, but urllib.quote ?

**Comment by bartTC** [comment]
@LennyLip could you give a better example here? I can't parse which of your 5 (!) `test` strings need to be quoted. FWIW I changed the internal Wiki lib to a recent one, maybe that fixed the problem.
